# See https://doc.rust-lang.org/cargo/reference/config.html#configuration-format for details.

[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
runner = "llvm-objdump -d"      # A wrapper to run executables. Or in this case, disassemble them.
rustflags = ["-C", "link-arg=-Tminimal.ld"]
